name: Code Coverage

on:
  push:
    paths:
      - "**/workflows/coverage.yml"
      - "**/Source/**"
      - "**/Tests/**"
      - "**/ThirdParty/**"
      - "**/CMakeLists.txt"
      - "**/.gitmodules"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install lcov
      run: sudo apt-get install -y lcov

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --target LuaBridgeTestsCoverage -- -j4

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ${{runner.workspace}}/build/coverage/Merged.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
